import mongoose from 'mongoose';
import { TEACHER_STATUS } from '../config/constants.js';

const teacherSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
    fullName: { type: String, required: true },
    profilePhoto: String,
    gender: { type: String, enum: ['male', 'female', 'other'] },
    dateOfBirth: Date,
    address: String,
    state: String,
    city: String,
    pincode: String,
    email: String,
    bio: String,
    teachingStyle: String,
    qualification: {
      highestQualification: String,
      instituteName: String,
      passingYear: Number,
      hasBEd: { type: Boolean, default: false },
      teachingCertification: String,
      additionalCertifications: [String],
      certificateUrl: String,
    },
    experience: {
      totalYears: Number,
      isFresher: { type: Boolean, default: false },
      teachingModes: [String],
      experienceTypes: [String],
      summary: String,
      resumeUrl: String,
    },
    subjects: [String],
    classes: [String],
    boards: [String],
    languages: [String],
    documents: {
      aadhaar: String,
      qualificationCert: String,
      experienceProof: String,
      resume: String,
      additional: [String],
    },
    demoVideo: {
      url: String,
      duration: Number,
      status: { type: String, enum: ['pending', 'approved', 'rejected'], default: 'pending' },
    },
    applicationStatus: {
      type: String,
      enum: Object.values(TEACHER_STATUS),
      default: TEACHER_STATUS.DRAFT,
    },
    rejectionReason: String,
    reapplyAfter: Date,
    onboardingStep: { type: Number, default: 0 },
    availabilityStatus: {
      type: String,
      enum: ['online', 'offline', 'busy'],
      default: 'offline',
    },
    availabilitySlots: [{
      day: { type: String, enum: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] },
      startTime: String,
      endTime: String,
      subjects: [String],
      repeatWeekly: { type: Boolean, default: true },
    }],
    bankDetails: {
      accountHolder: String,
      accountNumber: String,
      ifsc: String,
      bankName: String,
      isVerified: { type: Boolean, default: false },
    },
    wallet: {
      totalPoints: { type: Number, default: 0 },
      withdrawableBalance: { type: Number, default: 0 },
      pendingConversion: { type: Number, default: 0 },
    },
    metrics: {
      totalSessions: { type: Number, default: 0 },
      missedRequests: { type: Number, default: 0 },
      rating: { type: Number, default: 0 },
      ratingCount: { type: Number, default: 0 },
      responseSpeed: { type: Number, default: 0 },
      acceptanceRate: { type: Number, default: 100 },
      completionRate: { type: Number, default: 100 },
      performanceScore: { type: Number, default: 0 },
      todayEarnings: { type: Number, default: 0 },
      weeklyLiveTarget: { type: Number, default: 0 },
      weeklyLiveCompleted: { type: Number, default: 0 },
      streak: { type: Number, default: 0 },
    },
    interview: {
      scheduledAt: Date,
      slotId: { type: mongoose.Schema.Types.ObjectId, ref: 'Interview' },
      status: String,
      notes: String,
      recordingUrl: String,
    },
    isApproved: { type: Boolean, default: false },
    adminPriority: { type: Number, default: 0 },
  },
  { timestamps: true }
);

export default mongoose.model('Teacher', teacherSchema);
